# ..streamlit/secrets.toml
# url = "snowflake://YO39805@uiweywa-yo39805/"
user = "<user>"
account_identifier = "uiweywa-yo39805"
password = "<password>"
database_name = "snowflake_sample_data"
schema_name = "tpcds_sf10tcl"