# ..streamlit/secrets.toml

#[connections.snowflake]
url = "snowflake://YO39805@uiweywa-yo39805/"

#[connections.snowflake.create_engine_kwargs.connect_args]
user = "<user>"
account_identifier = "uiweywa-yo39805"
password = "<pass>"
#authenticator = "externalbrowser"
#warehouse = "COMPUTE_WH"
#role = "ACCOUNTADMIN"
#client_session_keep_alive = true
